title: The Nederlandse Testdag 2018
author:
email:
description: > # this means to ignore newlines until "baseurl:"
  The Nederlandse Testdag 2018

# twitter_username: macrod68
# github_username:  macrod68

sass:
    style: compressed
