title: Nederlandse Testdag 2019
author:
email:
description: > # this means to ignore newlines until "baseurl:"
  Nederlandse Testdag 2019

# twitter_username: macrod68
# github_username:  macrod68

sass:
    style: compressed
